### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by kkkkkkkwwwwwww** [arash-dehghan/NeurADP-Order-Dispatching#1]
Hello Professor, I am missing order data 1--5 when I run prepared--data with the original dataset, how do I get this part of the data, also, the dataset you provided are processed data but I can't run this data successfully in run.py (due to the lack of some pickle operations and parameters in the previous data prepared--data), can you please give me some guidance?

**Comment by arash-dehghan** [comment]
Hello, you can run the files as follows: (1) go to the google drive with the datasets (link in the readme file), and download the "datasets" folder. Move this downloaded folder to the data folder, so it should be data/datasets/...  (for example data/datasets/Brooklyn/...). (2) run the prepare_data.py file in the conda environment specified in the readme file. This will create generations files. You can specify the details of the generations file you want to create via the prepare_data.py file (for example, which city to utilize, etc.). (3) go to src folder and run the run.py file. Again you can specify the details of the simulation run (such as city, delay time, etc.). Let me know if you have any further questions.
